FROM ubuntu:18.04
RUN apt-get update && apt-get install -y build-essential wget libssl-dev p7zip-full && apt-get remove cmake

RUN cd /usr/local/src && \
    wget https://github.com/Kitware/CMake/releases/download/v3.27.7/cmake-3.27.7.tar.gz && \
    tar xzvf cmake-3.27.7.tar.gz && \
    cd cmake-3.27.7 && \
    ./bootstrap && \
    make && \
    make install